#!/usr/bin/env python3
import os
import sys

here = os.path.dirname(os.path.realpath(__file__))
command = "PYTHONPATH={}:$PYTHONPATH {}/bin/proof_leader {}".format(here, here, ' '.join(sys.argv[1:]))

os.system(command)
